#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','l','i','n','u',
        'x','-','a','n','d','r','o','i','d','e','a','b','i','-','g','c','c',' ',
        '-','I','.',' ','-','I','.','.',' ','-','I','.','.','/','i','n','c','l',
        'u','d','e',' ',' ','-','f','P','I','C',' ','-','D','O','P','E','N','S',
        'S','L','_','P','I','C',' ','-','D','O','P','E','N','S','S','L','_','T',
        'H','R','E','A','D','S',' ','-','D','_','R','E','E','N','T','R','A','N',
        'T',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D','H','A',
        'V','E','_','D','L','F','C','N','_','H',' ','-','m','a','n','d','r','o',
        'i','d',' ','-','I','/','U','s','e','r','s','/','m','c','c','r','a','e',
        '/','D','e','s','k','t','o','p','/','a','n','d','r','o','i','d','-','n',
        'd','k','-','r','1','0','e','/','p','l','a','t','f','o','r','m','s','/',
        'a','n','d','r','o','i','d','-','1','8','/','a','r','c','h','-','a','r',
        'm','/','u','s','r','/','i','n','c','l','u','d','e',' ','-','B','/','U',
        's','e','r','s','/','m','c','c','r','a','e','/','D','e','s','k','t','o',
        'p','/','a','n','d','r','o','i','d','-','n','d','k','-','r','1','0','e',
        '/','p','l','a','t','f','o','r','m','s','/','a','n','d','r','o','i','d',
        '-','1','8','/','a','r','c','h','-','a','r','m','/','u','s','r','/','l',
        'i','b',' ','-','O','3',' ','-','f','o','m','i','t','-','f','r','a','m',
        'e','-','p','o','i','n','t','e','r',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: android"
    #define DATE "built on: Sat Jul 15 12:28:08 2017"
#endif
